In [1]:
import pandas as pd
import os

df_list = []
for file in os.listdir('./data/'):
    if file[-3:] != "csv":
        continue

    print(f"Reading file: {file}")
    df_list.append(pd.read_csv(f"./data/{file}", index_col=False))

Reading file: 2011.csv
Reading file: 2012.csv
Reading file: 2013.csv
Reading file: 2014.csv
Reading file: 2015.csv

In [4]:
rows = 0
cols = 0
for df in df_list:
    rows += df.shape[0]
    cols += df.shape[1]
print(rows)
print(cols)
df_all = pd.concat(df_list, ignore_index=True, join="inner")
df_all.shape

2380047
1763

(2380047, 159)

In [5]:
df_all

,Unnamed: 0,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,...,_EDUCAG,_INCOMG,_TOTINDA,_RFSEAT2,_RFSEAT3,_PNEUMO2,DRNKANY5,DROCDY3_,_RFBING5,_AIDTST3
0,0,1.0,1.0,b'01202011',b'01',b'20',b'2011',120.0,2.011000e+09,2.011000e+09,...,2.0,2.0,2.0,1.0,1.0,NaN,1.0,4.300000e+01,1.0,2.0
1,1,1.0,1.0,b'01142011',b'01',b'14',b'2011',120.0,2.011000e+09,2.011000e+09,...,1.0,3.0,2.0,9.0,9.0,NaN,9.0,9.000000e+02,9.0,NaN
2,2,1.0,1.0,b'01062011',b'01',b'06',b'2011',120.0,2.011001e+09,2.011001e+09,...,4.0,3.0,1.0,1.0,1.0,9.0,1.0,1.400000e+01,1.0,2.0
3,3,1.0,1.0,b'02012011',b'02',b'01',b'2011',120.0,2.011001e+09,2.011001e+09,...,2.0,9.0,9.0,9.0,9.0,9.0,9.0,9.000000e+02,9.0,NaN
4,4,1.0,1.0,b'02012011',b'02',b'01',b'2011',120.0,2.011001e+09,2.011001e+09,...,1.0,1.0,1.0,1.0,1.0,NaN,2.0,5.397605e-79,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2380042,441451,72.0,11.0,b'12162015',b'12',b'16',b'2015',1100.0,2.015005e+09,2.015005e+09,...,1.0,2.0,2.0,1.0,1.0,2.0,2.0,5.397605e-79,1.0,2.0
2380043,441452,72.0,11.0,b'12142015',b'12',b'14',b'2015',1100.0,2.015005e+09,2.015005e+09,...,3.0,1.0,1.0,1.0,1.0,NaN,2.0,5.397605e-79,1.0,1.0
2380044,441453,72.0,11.0,b'12232015',b'12',b'23',b'2015',1200.0,2.015005e+09,2.015005e+09,...,2.0,3.0,9.0,9.0,9.0,9.0,1.0,7.000000e+00,1.0,NaN
2380045,441454,72.0,11.0,b'12152015',b'12',b'15',b'2015',1100.0,2.015005e+09,2.015005e+09,...,3.0,1.0,2.0,1.0,1.0,NaN,2.0,5.397605e-79,1.0,2.0
2380046,441455,72.0,11.0,b'12152015',b'12',b'15',b'2015',1100.0,2.015005e+09,2.015005e+09,...,4.0,1.0,1.0,1.0,1.0,NaN,2.0,5.397605e-79,1.0,1.0

In [3]:
for col in df_all.columns:
    print(col)

Unnamed: 0
_STATE
FMONTH
IDATE
IMONTH
IDAY
IYEAR
DISPCODE
SEQNO
_PSU
CTELENUM
NUMADULT
NUMMEN
NUMWOMEN
GENHLTH
PHYSHLTH
MENTHLTH
POORHLTH
HLTHPLN1
PERSDOC2
MEDCOST
CHECKUP1
CVDINFR4
CVDCRHD4
CVDSTRK3
ASTHMA3
ASTHNOW
CHCSCNCR
CHCOCNCR
HAVARTH3
ADDEPEV2
CHCKIDNY
DIABETE3
SMOKE100
SMOKDAY2
STOPSMK2
LASTSMK2
USENOW3
VETERAN3
MARITAL
CHILDREN
EDUCA
INCOME2
WEIGHT2
HEIGHT3
NUMHHOL2
NUMPHON2
CPDEMO1
RENTHOM1
SEX
PREGNANT
EXERANY2
QLACTLM2
USEEQUIP
SEATBELT
FLSHTMY2
IMFVPLAC
PNEUVAC3
ALCDAY5
AVEDRNK2
DRNK3GE5
MAXDRNKS
HIVTST6
HIVTSTD3
PDIABTST
PREDIAB1
DIABAGE2
INSULIN
BLDSUGAR
FEETCHK2
DOCTDIAB
CHKHEMO3
FEETCHK
EYEEXAM
DIABEYE
DIABEDU
PAINACT2
QLMENTL2
QLSTRES2
QLHLTH2
HADMAM
HOWLONG
PROFEXAM
LENGEXAM
HADPAP2
LASTPAP2
HADHYST2
PSATEST1
PSATIME
BLDSTOOL
LSTBLDS3
HADSIGM3
HADSGCO1
LASTSIG3
ASTHMAGE
ASATTACK
ASERVIST
ASDRVIST
ASRCHKUP
ASACTLIM
ASYMPTOM
ASNOSLEP
ASTHMED3
ASINHALR
HPVADVC2
HPVADSHT
SCNTPAID
SCNTWRK1
SCNTLPAD
SCNTLWK1
EMTSUPRT
LSATISFY
RCSGENDR
RCSRLTN2
CASTHDX2
CASTHNO2
CTELNUM1
CELLFON2
CADULT
PVTRESD2
CSTATE
LANDLINE
QSTVER
QSTLANG
MSCODE
_STSTR
_STRWT
_RAWRAKE
_WT2RAKE
_CLLCPWT
_LLCPWT
_RFHLTH
_HCVU651
_LTASTH1
_CASTHM1
_ASTHMS1
_DRDXAR1
_SMOKER3
_RFSMOK3
_AGEG5YR
_AGE65YR
_AGE_G
HTIN4
HTM4
WTKG3
_BMI5
_BMI5CAT
_RFBMI5
_CHLDCNT
_EDUCAG
_INCOMG
_TOTINDA
_RFSEAT2
_RFSEAT3
_PNEUMO2
DRNKANY5
DROCDY3_
_RFBING5
_AIDTST3